name = "DFOTools"
uuid = "72b80161-3157-4d20-81b3-e90aa1aa28f2"
authors = ["Sacha Benarroch-Lelong"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
